### ISSUE TITLE
Please plumb the main matrix channel with Libera

### ISSUE THREAD

**Issue by cornfeedhobo** [c3os-io/c3os#30]
This seems like an interesting project, but I don't want to use matrix.

Since matrix has a long standing bridge to libera (and previously at freenode), it'd be cool if this project ["plumbed"](https://matrix.org/bridges/) an identical channel on libera.

![image](https://imgs.xkcd.com/comics/team_chat_2x.png)

**Comment by mudler** [comment]
> @mudler Hey, thanks for the prompt reply and being into this. Before I send you in the wrong direction, do you have anyone on your team that already has a registered account on Libera?

I'll ask around tomorrow
> 
> For now I've gone ahead and made a channel, so I have Ops and can help you through the plumbing process, but it's synchronous, so we'll have to connect on chat. I think you can message me with `/msg cornfeedhobo:libera.chat ...`

That sounds great, thanks! I've sent you a dm there, let's see if this works out

**Comment by mudler** [comment]
Closing as now we are also on libera chat! Thanks @cornfeedhobo for the support!
