### ISSUE TITLE
C3OS should use sematic versioning

### ISSUE THREAD

**Issue by paynejacob** [c3os-io/c3os#83]
As C3OS becomes more decentralized as a toolset understanding compatibility will become more important. This would also allow us to control upgrades better as semver ranges could be used to prevent users from upgrading to versions with breaking changes.

**Comment by paynejacob** [comment]
I am wondering if we should only publish the version of the plugin and treat c3os as any other dependency.

e.g. the k3s provider would publish a tag for a k8s version and the k3s provider plugin version but the c3os version is excluded.  If there is a need to update c3os in the k3s provider image we would publish a new patch version of the k3s provider to upgrade c3os.

**Comment by mudler** [comment]
yep, that would work too, I'm just little concerned that generally it is cumbersome either way, but I guess we have to live with it. 

problem is - when you bake an ISO currently we override the version, so you loose somehow the version that was used to build against. or we either have yet-another-field in the OS release to track this explicitly, or be embedded somehow in the version

**Comment by paynejacob** [comment]
I like the idea of the os release having a different key for all the versions.  that way we can just  append our version and it becomes  like a package manifest.  As a user I want the working version of a an image, e.g. core-alpine-k3s and I want to be able to role back to a stable version if that ones messes up.  I don't care why it failed I just want to know what I am installing.  The os release file is where a developer would look if they  want to debug why an image is faulty.

**Comment by paynejacob** [comment]
The permutations make sense for the flavor version and k8s version because I may want to mix and match those but the provider version is just to track how to roll back.

**Comment by mudler** [comment]
I think I got almost all the bits now in https://github.com/c3os-io/provider-c3os/tree/releases , the release is: `v(provider version)-k3sv(k3s version)` for the image tag. when it comes the os-release file the FLAVOR/VARIANT is annotated and the OS_VERSION contains the k3s version as well so to be able to diff against to it easily. 

Just waiting for CI checks and a release test, we can always go back and change it if we don't see it fit

**Comment by mudler** [comment]
What is left is to manual QA provider-c3os release, update docs, and try to tag #49 on both

**Comment by mudler** [comment]
v0.57 is available
